version: "3.7"

services:

      challenge-bravo-db:
        image: mysql:5.7.5
        container_name: db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: application